version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  ml-engine:
    build: ./ml-engine
    ports:
      - "5001:5001"
    env_file:
      - ./ml-engine/.env
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3000:3000"

    # Required for React to run in a container without exiting
    stdin_open: true 
    tty: true
    depends_on:
      - server
      - ml-engine